PortieraChangeNameOther=fopen('1122Specific.xml','r');
newFile=fopen('1122SpecificNew.xml','w');
allOldNames={};
oldNamesToNewNames=containers.Map({'CYTOCHROME__45__C__45__OXIDASE__45__RXN','_3__45__ISOPROPYLMALDEHYDROG__45__RXN','RXN0__45__2381','RXN0__45__2382','TRYPSYN__45__RXN','HEMEOSYN__45__RXN','IGPSYN__45__RXN', ...
    'PHOSPHAGLYPSYN__45__RXN','PRTRANS__45__RXN','PRAISOM__45__RXN','PGPPHOSPHA__45__RXN','RXN__45__8141','ANTHRANSYN__45__RXN','RXN0__45__7012','_1__46__8__46__1__46__4__45__RXN','RXN__45__8629','CARDIOLIPSYN__45__RXN','RXN__45__7716','RXN0__45__1132', ...
    'RXN__45__7719','DIHYDLIPOXN__45__RXN','RXN0__45__1134','RXN__45__13323','RXN__45__12583','_2__46__5__46__1__46__32__45__RXN','RXN__45__12508','RXNARA__45__8002','BRANCHED__45__CHAINAMINOTRANSFERILEU__45__RXN','RXN0__45__1133','DIHYDLIPACETRANS__45__RXN', ...
    'RXN__45__12496','RXN1F__45__151','BRANCHED__45__CHAINAMINOTRANSFERLEU__45__RXN','GUANYL__45__KIN__45__RXN','RXN1F__45__148','GLUCOKIN__45__RXN','RXN1F__45__150','RXN__45__1685','RXN66__45__521','RXN__45__7968','RXN__45__13482','PRPPSYN__45__RXN', ...
    'ORNCARBAMTRANSFER__45__RXN','GLU6PDEHYDROG__45__RXN','RXN__45__10','ARGSUCCINSYN__45__RXN','RXN__45__9952','RXN__45__13455','IMP__45__DEHYDROG__45__RXN','_2OXOGLUTDECARB__45__RXN','GDPKIN__45__RXN','CARBPSYN__45__RXN','RXN0__45__1147','GLUTAMIN__45__RXN', ...
    'RXN__45__13202','BRANCHED__45__CHAINAMINOTRANSFERVAL__45__RXN','_2__46__5__46__1__46__19__45__RXN','_3__45__DEHYDROQUINATE__45__SYNTHASE__45__RXN','HISTALDEHYD__45__RXN','CHORISMATE__45__SYNTHASE__45__RXN','HISTOLDEHYD__45__RXN', ...
    'SHIKIMATE__45__5__45__DEHYDROGENASE__45__RXN','HISTIDPHOS__45__RXN','DAHPSYN__45__RXN','NADH__45__DEHYDROG__45__A__45__RXN','SHIKIMATE__45__KINASE__45__RXN','ADENYLOSUCCINATE__45__SYNTHASE__45__RXN','_3__45__DEHYDROQUINATE__45__DEHYDRATASE__45__RXN', ...
    'AMPSYN__45__RXN','RXN0__45__5098','ADENYL__45__KIN__45__RXN','RXN__45__11355','RXN0__45__947','CHORISMATEMUT__45__RXN','RXN__45__12243','RXN__45__12244','ASPARTATEKIN__45__RXN','ASPARTATE__45__SEMIALDEHYDE__45__DEHYDROGENASE__45__RXN', ...
    'HOMOSERDEHYDROG__45__RXN','ACETYLORNTRANSAM__45__RXN','HOMOSERKIN__45__RXN','THRESYN__45__RXN','_2__46__7__46__7__46__8__45__RXN','DNA__45__DIRECTED__45__DNA__45__POLYMERASE__45__RXN','RXN__45__15007','RXN__45__12730','DIAMINOPIMEPIM__45__RXN', ...
    'SUCCINYLDIAMINOPIMTRANS__45__RXN','HOMOCYSMET__45__RXN','RXN__45__14014','DIHYDRODIPICSYN__45__RXN','DNA__45__DIRECTED__45__RNA__45__POLYMERASE__45__RXN','TETHYDPICSUCC__45__RXN','DIAMINOPIMDECARB__45__RXN','RXN0__45__949','GLUTAMIDOTRANS__45__RXN', ...
    'RXN__45__14959','SUCCDIAMINOPIMDESUCC__45__RXN','RXN__45__14957','RXN__45__14950','RXN__45__15003','GMP__45__SYN__45__GLUT__45__RXN','ATPPHOSPHORIBOSYLTRANS__45__RXN','_1__46__5__46__1__46__20__45__RXN','RXN__45__15005','HISTPRATPHYD__45__RXN', ...
    'GMP__45__SYN__45__NH3__45__RXN','RXN__45__15006','HISTCYCLOHYD__45__RXN','RXN__45__15004','SELENOCYSTEINE__45__LYASE__45__RXN','CARBAMATE__45__KINASE__45__RXN','PRIBFAICARPISOM__45__RXN','RXN__45__13456','IMIDPHOSDEHYD__45__RXN','HISTAMINOTRANS__45__RXN', ...
    'THREDEHYD__45__RXN','RXN__45__15122','PABASYN__45__RXN','_1__46__10__46__2__46__2__45__RXN','ACETOOHBUTREDUCTOISOM__45__RXN','ARGSUCCINLYA__45__RXN','SUCCINATE__45__DEHYDROGENASE__45__UBIQUINONE__45__RXN','ACETOLACTREDUCTOISOM__45__RXN', ...
    'DIHYDROXYISOVALDEHYDRAT__45__RXN','RXN__45__13163','DIHYDROXYMETVALDEHYDRAT__45__RXN','_3__45__ISOPROPYLMALISOM__45__RXN','RXN__45__8991','ACETOOHBUTSYN__45__RXN','ACETOLACTSYN__45__RXN','R__45__2__45__METHYLMALATE__45__DEHYDRATASE__45__RXN', ...
    '_2__45__ISOPROPYLMALATESYN__45__RXN','RXN__45__13158','HOMOCYSMETB12__45__RXN','_3__45__ISOPROPYLMALDEHYDROG__45__RXN','RXN0__45__5268','RXN__45__14986','RXN__45__14954'}, ...
    {'cytochrome c oxidase','3-isopropylmalate dehydrogenase','tryptophan synthase, alfa subunit','tryptophan synthase, beta subunit','tryptophan synthase','heme O synthase','indole-3-glycerol phosphate synthase','phosphatidylglycerophosphate synthase', ...
    'anthranilate phosphoribosyltransferase','phosphoribosylanthranilate isomerase','phosphatidylglycerophosphatase','cardiolipin synthase','anthranilate synthase','cardiolipin synthase 3','lipoamide dehydrogenase','lipoamide dehydrogenase', ...
    'cardiolipin synthase','lipoamide dehydrogenase','lipoamide dehydrogenase','lipoamide dehydrogenase','dihydrolipoamide dehydrogenase','pyruvate dehydrogenase','phytoene synthase','pyruvate dehydrogenase: aceE','phytoene synthase', ...
    'pyruvate dehydrogenase: aceE','phytoene synthase','branched-chain amino-acid aminotransferase','AceF','dihydrolipoyllysine-residue acetyltransferase','lycopene beta-cyclase','lycopene beta-cyclase','branched-chain amino-acid aminotransferase', ...
    'guanylate kinase','lycopene beta-cyclase','glucokinase','lycopene beta-cyclase','glucokinase','glucokinase','shikimate dehydrogenase','ornithine carbamoyltransferase','ribose-phosphate diphosphokinase','ornithine carbamoyltransferase', ...
    'glucose 6-phosphate-1-dehydrogenase','argininosuccinate synthetase','argininosuccinate synthase','6-phosphogluconate dehydrogenase','N-acetylglutaminylglutamine synthase','IMP dehydrogenase','2-oxoglutarate decarboxylase','nucleoside diphosphate kinase', ...
    'carbamoyl phosphate synthetase','dihydrolipoyllysine-residue succinyltransferase','glutaminase','carbamoyl phosphate synthetase','branched-chain amino-acid aminotransferase','3-phosphoshikimate-1-carboxyvinyltransferase','3-dehydroquinate synthase', ...
    'histidinal dehydrogenase','chorismate synthase','histidinol dehydrogenase','shikimate dehydrogenase','histidinol-phosphatase','3-deoxy-7-phosphoheptulonate synthase','NADH:ubiquinone oxidoreductase I','shikimate kinase','adenylosuccinate synthetase', ...
    '3-dehydroquinate dehydratase','adenylosuccinate lyase','lipoyl-protein ligase A','adenylate kinase','15-cis phytoene desaturase','lipoyl(octanoyl) transferase','chorismate mutase','15-cis phytoene desaturase','15-cis phytoene desaturase', ...
    'aspartate kinase III','aspartate semialdehyde dehydrogenase','homoserine dehydrogenase','acetylornithine aminotransferase/N-succinyldiaminopimelate aminotransferase','homoserine kinase','threonine synthase','polyribonucleotide nucleotidyltransferase','DNA-directed DNA polymerase', ...
    'acetylornithine transaminase','5-methyltetrahydropteroyltriglutamate--homocysteine methyltransferase','diaminopimelate epimerase','succinyldiaminopimelate transaminase','5-methyltetrahydropteroyltriglutamate?homocysteine S-methyltransferase', ...
    '4-hydroxy-tetrahydrodipicolinate reductase','4-hydroxy-tetrahydrodipicolinate synthase','DNA-directed RNA polymerase','2,3,4,5-tetrahydropyridine-2,6-dicarboxylate N-succinyltransferase','diaminopimelate decarboxylase','lipoyl synthase', ...
    'Pentosyltransferases','lipoyl synthase','succinyl-diaminopimelate desuccinylase','lipoyl synthase','lipoyl synthase','Acid--amino-acid ligases','GMP synthase','ATP phosphoribosyltransferase','methylenetetrahydrofolate reductase [NAD(P)H]', ...
    'acetylglutamate kinase','phosphoribosyl-ATP diphosphatase','GMP synthetase','N-acetyl-?-glutamyl-phosphate reductase','phosphoribosyl-AMP cyclohydrolase','L-2-aminoadipate carrier protein]-lysine/ornithine hydrolase','selenocysteine lyase','carbamate kinase', ...
    '1-(5-phosphoribosyl)-5-[(5-phosphoribosylamino)methylideneamino]imidazole-4-carboxamide isomerase','N-acetylglutaminylglutamine amide synthase','imidazoleglycerol-phosphate dehydratase','histidinol-phosphate transaminase','threonine ammonia-lyase', ...
    'threonine dehydratase','aminodeoxychorismate synthase','quinol?cytochrome-c reductase','ketol-acid reductoisomerase','argininosuccinate lyase','succinate dehydrogenase (quinone)','ketol-acid reductoisomerase','dihydroxy-acid dehydratase', ...
    '3-isopropylmalate dehydratase','dihydroxy-acid dehydratase','isopropylmalate isomerase','isopropylmalate isomerase','acetolactate synthase','acetolactate synthase','2-methylmalate dehydratase','2-isopropylmalate synthase','3-isopropylmalate dehydrogenase', ...
    'methionine synthase','3-isopropylmalate dehydrogenase','ubiquinol oxidase (H+-transporting)','3-isopropylmalate dehydrogenase','CoA-transferases'});
while(~feof(PortieraChangeNameOther))
    PortieraReading=fgetl(PortieraChangeNameOther);
    newFileLine=PortieraReading;
    if(regexp(PortieraReading,'species id'))
        
    end
    if(regexp(PortieraReading,'reaction id'))
        firstLocation=regexp(PortieraReading,'reaction id="')+12;
        secondLocation=regexp(PortieraReading,'" name');
        oldName=PortieraReading(firstLocation+1:secondLocation-1);
        allOldNames{end+1}=oldName;
        if(isKey(oldNamesToNewNames,oldName))
            newName=oldNamesToNewNames(oldName);
            newFileLine=[PortieraReading(1:firstLocation) newName PortieraReading(secondLocation:end)];
        end
    end
    fprintf(newFile,[newFileLine '\n']);
end
fclose(PortieraChangeNameOther);
fclose(newFile);

writeFID=fopen('test.txt','w');
for i=1:length(allOldNames)
    fprintf(writeFID,'%s',allOldNames{i});
    if(isKey(oldNamesToNewNames,allOldNames{i}))
        fprintf(writeFID,'\t%s\n',oldNamesToNewNames(allOldNames{i}));
    else
        fprintf(writeFID,'\n');
    end
end
fclose(writeFID);